# Generated by Django 6.0 on 2025-12-07 03:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Endpoint name', max_length=255)),
                ('app', models.CharField(choices=[('products', 'Products'), ('orders', 'Orders'), ('logistics', 'Logistics'), ('finance', 'Finance'), ('promotions', 'Promotions'), ('analytics', 'Analytics')], help_text='Django app', max_length=50)),
                ('api_type', models.CharField(choices=[('rest', 'REST API'), ('soap', 'SOAP API')], help_text='API type', max_length=10)),
                ('url_path', models.CharField(help_text='URL path', max_length=500)),
                ('http_method', models.CharField(blank=True, help_text='HTTP method (for REST)', max_length=20)),
                ('description', models.TextField(help_text='Endpoint description')),
                ('request_example', models.TextField(blank=True, help_text='Example request')),
                ('response_example', models.TextField(blank=True, help_text='Example response')),
                ('is_active', models.BooleanField(default=True, help_text='Is endpoint active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'API Endpoint',
                'verbose_name_plural': 'API Endpoints',
                'ordering': ['app', 'api_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('category', models.CharField(blank=True, max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order', 'question'],
            },
        ),
        migrations.CreateModel(
            name='SetupGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Guide title', max_length=255)),
                ('guide_type', models.CharField(choices=[('installation', 'Installation'), ('configuration', 'Configuration'), ('deployment', 'Deployment'), ('troubleshooting', 'Troubleshooting')], max_length=50)),
                ('content', models.TextField(help_text='Guide content (supports Markdown)')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Setup Guide',
                'verbose_name_plural': 'Setup Guides',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='APIChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deprecated', 'Deprecated'), ('removed', 'Removed')], max_length=20)),
                ('version', models.CharField(help_text='Version number', max_length=50)),
                ('description', models.TextField(help_text='Change description')),
                ('breaking_change', models.BooleanField(default=False, help_text='Is this a breaking change?')),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('changed_by', models.CharField(blank=True, help_text='Who made the change', max_length=255)),
                ('endpoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='documentation.apiendpoint')),
            ],
            options={
                'verbose_name': 'API Change Log',
                'verbose_name_plural': 'API Change Logs',
                'ordering': ['-changed_at'],
            },
        ),
    ]
